stages:
  - lint
  - test

clippy:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings
    - cargo clippy --no-default-features -- -D warnings

rust-stable:
  stage: test
  image: rust:latest
  script:
    - cargo test

rust-1_59:
  stage: test
  image: rust:1.59
  script:
    - cargo test

rust-beta:
  stage: test
  image: instrumentisto/rust:beta
  script:
    - cargo test

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  allow_failure: true
  script:
    - cargo test
    - cargo test --no-default-features
